import Link from 'next/link';
import { Award, Shield, Heart, MessageCircle, ArrowRight } from 'lucide-react';
export const metadata = { title: 'Sobre — Beto Baltazar Corretor' };
export default function SobrePage() {
  return (
    <div className="bg-paper">
      <section className="bg-cream/40 border-b border-border"><div className="max-w-7xl mx-auto px-6 md:px-8 py-16 md:py-24"><p className="text-xs tracking-[4px] text-terra uppercase mb-4 font-semibold">Quem é</p><h1 className="font-display text-5xl md:text-6xl font-bold text-ink mb-6">Beto Baltazar.<br/><span className="text-terra">Corretor por vocação.</span></h1><p className="text-lg text-ink-soft/80 max-w-xl">Há mais de 15 anos ajudando famílias e empreendedores a encontrarem o imóvel certo em Capão Bonito.</p></div></section>
      <section className="py-20 bg-white border-y border-border"><div className="max-w-3xl mx-auto px-6 md:px-8"><p className="text-xs tracking-[4px] text-terra uppercase mb-4 font-semibold">A trajetória</p><div className="space-y-5 text-lg text-ink-soft/85 leading-relaxed"><p>Cada imóvel guarda uma história — e é capaz de começar outras. Foi essa percepção que me fez escolher essa profissão.</p><p>Em Capão Bonito conheço bairros, ruas e famílias. Esse conhecimento de quem está aqui há tempo é o que permite encontrar o imóvel <span className="text-terra font-semibold">certo</span> para cada pessoa.</p><p>Trabalho sozinho, com dedicação em cada negociação. Você fala comigo do primeiro contato à entrega das chaves.</p></div></div></section>
      <section className="py-20 bg-paper"><div className="max-w-7xl mx-auto px-6 md:px-8"><div className="text-center mb-12"><p className="text-xs tracking-[4px] text-terra uppercase mb-3 font-semibold">Como trabalho</p><h2 className="font-display text-4xl font-bold text-ink">Três valores inegociáveis.</h2></div><div className="grid md:grid-cols-3 gap-6">{[{icon:<Award className="text-terra" size={28} strokeWidth={1.5}/>,title:'Curadoria',text:'Visito cada imóvel pessoalmente antes de incluir na carteira.'},{icon:<Shield className="text-ink" size={28} strokeWidth={1.5}/>,title:'Transparência',text:'Documentação revisada e contratos claros. Sem surpresas.'},{icon:<Heart className="text-terra" size={28} strokeWidth={1.5}/>,title:'Dedicação',text:'Acompanho cada negociação com atenção total ao detalhe.'}].map((v,i)=><div key={i} className="bg-white border border-border rounded-2xl p-8"><div className="w-14 h-14 bg-cream rounded-xl flex items-center justify-center mb-5">{v.icon}</div><h3 className="font-display text-xl font-semibold mb-3">{v.title}</h3><p className="text-sm text-ink-soft/75 leading-relaxed">{v.text}</p></div>)}</div></div></section>
      <section className="py-20 bg-ink text-white"><div className="max-w-3xl mx-auto px-6 text-center"><h2 className="font-display text-4xl font-bold mb-6">Vamos conversar?</h2><div className="flex flex-wrap gap-3 justify-center"><a href="https://wa.me/5515996897738" target="_blank" rel="noopener noreferrer" className="btn-primary btn-lg"><MessageCircle size={16}/> WhatsApp</a><Link href="/imoveis" className="inline-flex items-center gap-2 bg-white/10 hover:bg-white/20 border border-white/20 text-white px-7 py-3.5 rounded-lg text-sm font-medium transition group">Ver imóveis<ArrowRight size={14} className="group-hover:translate-x-1 transition-transform"/></Link></div></div></section>
    </div>
  );
}
